// <auto-generated />
using System;
using AgênciaVivaViagemWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgênciaVivaViagemWeb.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20211219001913_AgenciaMigration")]
    partial class AgenciaMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgênciaVivaViagemWeb.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("AgênciaVivaViagemWeb.Models.Promocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinosId")
                        .HasColumnType("int");

                    b.Property<int>("IdDestino")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinosId");

                    b.ToTable("Promocoes");
                });

            modelBuilder.Entity("AgênciaVivaViagemWeb.Models.Promocao", b =>
                {
                    b.HasOne("AgênciaVivaViagemWeb.Models.Destino", "Destinos")
                        .WithMany("Promocao")
                        .HasForeignKey("DestinosId");

                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("AgênciaVivaViagemWeb.Models.Destino", b =>
                {
                    b.Navigation("Promocao");
                });
#pragma warning restore 612, 618
        }
    }
}
